Repository rthadur/recaptcha, pull requests merged in 2021-07, with the labels that each got.

#388 Update README.md
  README.md
Labels: ready to pull

#394 Revert "Update README.md"
  README.md
Labels: awaiting review

#395 Revert "Revert "Update README.md""
  README.md
Labels: awaiting review, ready to pull

#396 Revert "Revert "Revert "Update README.md"""
  README.md
Labels: awaiting review, ready to pull
